### ISSUE TITLE
Could be clearer about needing root, using UDP packet for WoL would avoid the need

### ISSUE THREAD

**Issue by tv42** [mdlayher/wol#1]
Hi. Love me some low-level networking tools, nice to see people being interested in the topic.

Probably the most common command-line WoL client is http://gsd.di.uminho.pt/jpo/software/wakeonlan/ which is just a <300 line perl script that sends a UDP packet. The big benefit of that approach is not needing root privileges. I'm not aware of any modern-day WoL implementations that wouldn't wake up with a UDP packet. That would make this package a lot more practical to use, both on the command line and as a library.

**Comment by mdlayher** [comment]
Hi there!

I can definitely make the Client type use UDP instead, or perhaps offer both as different types. I'll take a look at doing so tomorrow!

**Comment by mdlayher** [comment]
I've changed the old `Client` type to `RawClient` and added a new `Client` which makes use of UDP sockets instead.  It's a bit strange because it's an empty struct, but I figure it will be more useful for those who want to pass a `Client` around their program.

Please do let me know if you have any more ideas for improvements.  Thanks for your time.

Fixed in 0e2d7119d93c0b6cab83829571fd865bed92fa1a.

**Comment by tv42** [comment]
Just tested the command-line tool, works perfectly with UDP, I'm throwing out the perl script. Thanks!
